### ISSUE TITLE
dependency change?

### ISSUE THREAD

**Issue by hinkelman** [oetr/racket-hdf5#1]
I'm brand new to Racket but was planning to try your hdf5 package. Unfortunately, I can't even get past the `raco pkg install` step. Is there something obvious that I should do to make it work? Thanks!

**Comment by oetr** [comment]
I updated dependencies without testing. You can also use the --force to ignore dependencies when installing:
raco pkg install --deps force hdf5

**Comment by hinkelman** [comment]
Thanks! I was able to install the package. I will now start slowly working through the examples.
